### ISSUE TITLE
Size of keyboard case?

### ISSUE THREAD

**Issue by nicolai86** [Biacco42/Ergo42#6]
Hey,

thanks for sharing this nice project!

I'm wondering which dimensions to use for the case files - can you add this information to the repository? Otherwise it's really tricky to build one yourself!

Best & Thanks,
Raphael

**Comment by Biacco42** [comment]
Sorry for my late reply.

The case design files hosts not only the shapes but also the dimensions. I designed the files on Adobe Illustrator and set the dimensions in mm. So you can check the dimensions in the ai file or the eps file.

Is it OK?

**Comment by nicolai86** [comment]
Thanks :)
